version: '3.8'

services:
  db:
    image: mysql
    container_name: lingiathotel-db
    restart: unless-stopped
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: lingiathotel_db
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_PASSWORD: password
      volumes: ./docker/mysql:/var/lib/mysql
